export const mealsSeedData = [
  {
    title: 'Kip Teriyaki Bowl',
    slug: 'kip-teriyaki-bowl',
    emoji: '🍗',
    tag: 'Afvallen',
    calories: 520,
    protein: 52,
    carbs: 48,
    fat: 14,
    priceInUSD: 8.49,
    ingredients: 'Kipfilet (halal), jasmijnrijst, broccoli, edamame, sojasaus, honing, gember, knoflook, sesamolie, sesamzaad',
    allergens: 'Soja, sesam',
    storage_instructions: 'Bewaar in de koelkast (max 2-3 dagen) of vries direct in na ontvangst (houdbaar tot 3 maanden). Opwarmen: 3 minuten in de magnetron op 700W.',
    halal: true,
    featured: true,
    sort_order: 1,
  },
  {
    title: 'Beef Rendang',
    slug: 'beef-rendang',
    emoji: '🥩',
    tag: 'Spiermassa',
    calories: 680,
    protein: 48,
    carbs: 62,
    fat: 22,
    priceInUSD: 9.49,
    ingredients: 'Rundvlees (halal), kokosmelk, rode peper, laos, citroengras, kurkuma, langkorrelige rijst, atjar, gebakken uitjes',
    allergens: 'Geen',
    storage_instructions: 'Bewaar in de koelkast (max 2-3 dagen) of vries direct in na ontvangst (houdbaar tot 3 maanden). Opwarmen: 3 minuten in de magnetron op 700W.',
    halal: true,
    featured: true,
    sort_order: 2,
  },
  {
    title: 'Zalm & Quinoa',
    slug: 'zalm-quinoa',
    emoji: '🐟',
    tag: 'Afvallen',
    calories: 490,
    protein: 44,
    carbs: 38,
    fat: 18,
    priceInUSD: 10.49,
    ingredients: 'Zalmfilet, quinoa, zoete aardappel, baby spinazie, citroen, dille, olijfolie, pijnboompitten',
    allergens: 'Vis',
    storage_instructions: 'Bewaar in de koelkast (max 2-3 dagen) of vries direct in na ontvangst (houdbaar tot 3 maanden). Opwarmen: 3 minuten in de magnetron op 700W.',
    halal: true,
    featured: true,
    sort_order: 3,
  },
  {
    title: 'Kip Shawarma XXL',
    slug: 'kip-shawarma-xxl',
    emoji: '🥙',
    tag: 'Aankomen',
    calories: 780,
    protein: 67,
    carbs: 72,
    fat: 20,
    priceInUSD: 9.99,
    ingredients: 'Kipfilet (halal), shawarma kruiden, basmatirijst, kikkererwten, tahini, tomaat, komkommer, knoflook, yoghurt',
    allergens: 'Sesam, zuivel',
    storage_instructions: 'Bewaar in de koelkast (max 2-3 dagen) of vries direct in na ontvangst (houdbaar tot 3 maanden). Opwarmen: 3 minuten in de magnetron op 700W.',
    halal: true,
    featured: true,
    sort_order: 4,
  },
  {
    title: 'Veggie Buddha Bowl',
    slug: 'veggie-buddha-bowl',
    emoji: '🥗',
    tag: 'Droogtrainen',
    calories: 420,
    protein: 28,
    carbs: 52,
    fat: 12,
    priceInUSD: 8.99,
    ingredients: 'Kikkererwten, quinoa, avocado, rode kool, wortel, komkommer, tahini, citroen, koriander',
    allergens: 'Sesam',
    storage_instructions: 'Bewaar in de koelkast (max 2-3 dagen) of vries direct in na ontvangst (houdbaar tot 3 maanden). Opwarmen: 3 minuten in de magnetron op 700W.',
    halal: true,
    featured: true,
    sort_order: 5,
  },
  {
    title: 'Pulled Chicken Wrap',
    slug: 'pulled-chicken-wrap',
    emoji: '🌯',
    tag: 'Droogtrainen',
    calories: 560,
    protein: 45,
    carbs: 50,
    fat: 16,
    priceInUSD: 8.79,
    ingredients: 'Kipfilet (halal), volkoren tortilla, BBQ saus, witte kool, wortel, mayonaise, jalapeno',
    allergens: 'Gluten, ei',
    storage_instructions: 'Bewaar in de koelkast (max 2-3 dagen) of vries direct in na ontvangst (houdbaar tot 3 maanden). Opwarmen: 3 minuten in de magnetron op 700W.',
    halal: true,
    featured: true,
    sort_order: 6,
  },
]
